### ISSUE TITLE
v1.1.0 breaks `nodeping-ansible`

### ISSUE THREAD

**Issue by andyundso** [NodePing/nodepingpy#1]
Hello!

The most recent release breaks `nodeping-ansible` and I am not sure if this was intentional or not.

v1.0.2:

```
import nodepingpy
>>> nodepingpy.checks
<module 'nodepingpy.checks' from '/home/apf/xxxx/.venv/lib/python3.13/site-packages/nodepingpy/checks.py'>
```

v1.1.0:

```
>>> import nodepingpy
>>> nodepingpy.checks
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    nodepingpy.checks
AttributeError: module 'nodepingpy' has no attribute 'checks'
```

Appears the syntax should be like that now:

```
>>> from nodepingpy import checks
>>> checks
<module 'nodepingpy.checks' from '/home/apf/xxxxx/.venv/lib/python3.13/site-packages/nodepingpy/checks.py'>
```

But again, not sure if this broken intentionally here or if an update to `nodeping-ansible` is outstanding on your side.

**Comment by NodePing** [comment]
Hi @andyundso .

I am going to close this issue. I have an update I am about to push for `nodeping-ansible` which will work with `nodepingpy` v1.1.0. If you find another issue with `nodeping-ansible`, please submit an issue in that repo.

Thank you for submitting this issue.

**Comment by NodePing** [comment]
@andyundso Please try the 4.0 release for the Ansible module:
https://github.com/NodePing/nodeping-ansible/releases/tag/4.0
